"""AGG-14 research/product experiment contracts.

This namespace is intentionally sender-free and default-off.  It creates
content-addressed evidence and plans only; it has no signer, RPC sender, Jito,
or live-trading integration.
"""

from .benchmarks import (
    AccelerationBenchmark,
    BenchmarkClass,
    BenchmarkMeasurement,
    ComparativeBenchmark,
    QuboBenchmark,
    QuantumModelExperiment,
    compare_measurements,
)
from .verifiability import FederatedExperiment, VerifiabilityPrototype
from .common import (
    EvidencePointer,
    EvidenceStatus,
    OFFLINE_RESEARCH_BOUNDARY,
    ResearchDisposition,
    ResearchFailure,
    ResearchOutcome,
    SourceKind,
    hash_json,
)
from .evidence import (
    AgentExperimentPlan,
    AgentRoleDecision,
    DefensiveToolBenchmark,
    DevelopmentWorkflowReceipt,
    HypothesisRecord,
    ResearchClaim,
    ResearchCopilotResult,
    ResearchEvidenceLibrary,
    ResearchExperimentManifest,
    ResearchSource,
    build_cited_research_result,
)
from .product import (
    ApplicationOrDisclosureReceipt,
    CashState,
    DataEvidenceApi,
    DataEvidenceArtifact,
    DataEvidenceKind,
    DataEvidenceResponse,
    KeeperAuthorization,
    KeeperOperation,
    PaymasterCapability,
    RevenueAttributionLedger,
    RevenueCashflow,
    RevenueCategory,
    SponsorBudget,
    SponsoredExecutionPlan,
    plan_keeper_operation,
    plan_sponsored_execution,
)
from .promotion import (
    PromotionDecisionKind,
    ResearchPromotionDecision,
    evaluate_research_promotion,
)

__all__ = [
    "AccelerationBenchmark",
    "AgentExperimentPlan",
    "AgentRoleDecision",
    "ApplicationOrDisclosureReceipt",
    "BenchmarkClass",
    "BenchmarkMeasurement",
    "CashState",
    "ComparativeBenchmark",
    "DataEvidenceApi",
    "DataEvidenceArtifact",
    "DataEvidenceKind",
    "DataEvidenceResponse",
    "DefensiveToolBenchmark",
    "DevelopmentWorkflowReceipt",
    "EvidencePointer",
    "EvidenceStatus",
    "FederatedExperiment",
    "HypothesisRecord",
    "KeeperAuthorization",
    "KeeperOperation",
    "OFFLINE_RESEARCH_BOUNDARY",
    "PaymasterCapability",
    "PromotionDecisionKind",
    "QuboBenchmark",
    "QuantumModelExperiment",
    "ResearchClaim",
    "ResearchCopilotResult",
    "ResearchDisposition",
    "ResearchEvidenceLibrary",
    "ResearchExperimentManifest",
    "ResearchFailure",
    "ResearchOutcome",
    "ResearchPromotionDecision",
    "ResearchSource",
    "RevenueAttributionLedger",
    "RevenueCashflow",
    "RevenueCategory",
    "SourceKind",
    "SponsorBudget",
    "SponsoredExecutionPlan",
    "VerifiabilityPrototype",
    "build_cited_research_result",
    "compare_measurements",
    "evaluate_research_promotion",
    "hash_json",
    "plan_keeper_operation",
    "plan_sponsored_execution",
]
