#!/bin/bash
# ============================================================
# Layer 4 — Linux Kernel TCP Tuning for HFT Solana Bots
# Fixes: TCP BBR congestion + TCP Fast Open
# Eliminates: packet-loss slow-start, 1-RTT handshake overhead
#
# Linux-only — this script is a no-op on macOS
# Run with sudo (or add to /etc/sysctl.conf for persistence):
#   sudo bash setup_sysctl_hft.sh
# ============================================================

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "⚠️  This script is for Linux only. Detected: $(uname -s)"
    exit 0
fi

set -euo pipefail

echo "=== Layer 4: Applying Linux TCP HFT tuning ==="

TUNE=(
    "net.core.default_qdisc=fq"              # Fair Queue — fixes bufferbloat
    "net.ipv4.tcp_congestion_control=bbr"    # Google BBR — ignores packet loss, max throughput
    "net.ipv4.tcp_fastopen=3"                # TFO: send data inside SYN handshake (saves 1 RTT)
    "net.ipv4.tcp_tw_reuse=1"                # Reuse TIME_WAIT sockets
    "net.ipv4.tcp_tw_recycle=1"
    "net.ipv4.tcp_syncookies=1"
    "net.core.rmem_max=26214400"             # 25 MB receive buffer
    "net.core.wmem_max=26214400"             # 25 MB send buffer (large unacked data pile-up for burst)
    "net.ipv4.tcp_rmem=4096 87380 26214400"
    "net.ipv4.tcp_wmem=4096 65536 26214400"
    "net.ipv4.tcp_mtu_probing=1"             # Recover path MTU on ICMP blackholes (Jito servers)
    "net.ipv4.tcp_no_metrics_save=1"         # Avoid stale RTT samples poisoning connection
)

for param in "${TUNE[@]}"; do
    key="${param%%=*}"
    val="${param##*=}"
    cur=$(sysctl -n "$key" 2>/dev/null || echo "?")
    echo "  $key: $cur → $val"
    sudo sysctl -w "$param" > /dev/null
done

echo ""
echo "=== Current TCP congestion control ==="
sysctl net.ipv4.tcp_congestion_control
sysctl net.ipv4.tcp_fastopen
sysctl net.core.rmem_max
sysctl net.core.wmem_max

echo ""
echo "=== Persisting to /etc/sysctl.conf ==="
sudo cp /etc/sysctl.conf /etc/sysctl.conf.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null || true
sudo tee /etc/sysctl.conf > /dev/null << 'SYSEOF'
# ── HFT Solana TCP tuning — Layer 4 (auto-generated by setup_sysctl_hft.sh) ──
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_tw_recycle=1
net.ipv4.tcp_syncookies=1
net.core.rmem_max=26214400
net.core.wmem_max=26214400
net.ipv4.tcp_rmem=4096 87380 26214400
net.ipv4.tcp_wmem=4096 65536 26214400
net.ipv4.tcp_mtu_probing=1
net.ipv4.tcp_no_metrics_save=1
SYSEOF
echo ">>> Done. Effective TCP stack is now BBR + Fast Open."
echo ">>> Verify anytime:  sysctl net.ipv4.tcp_congestion_control net.ipv4.tcp_fastopen"
