"""Canonical permit-bound RPC/Jito submission boundary."""

from .canonical import (
    CanonicalPermitBoundSender,
    CanonicalSenderConfig,
    CanonicalStatusReport,
    JitoCredentialMode,
    consolidate_submission_observations,
)
from .durable import DurableSubmissionResult, PermitBoundSubmissionService
from .permit_bound import (
    AsyncJsonHttpTransport,
    ErrorDisposition,
    HttpResponse,
    JitoSender,
    JitoUuidAuth,
    LivePermitIssuer,
    LiveSubmissionPolicy,
    PermitRequest,
    ResubmissionDecision,
    RpcSender,
    Sender,
    SignedPayload,
    SubmissionAck,
    SubmissionError,
    SubmissionErrorCode,
    SubmissionObservation,
    SubmissionPermit,
    SubmissionState,
    SubmissionStatusClient,
    TipAccountSnapshot,
    TipEvidence,
    TransportKind,
    classify_jito_bundle_status,
    classify_jito_inflight_status,
    classify_signature_statuses,
    inspect_exactly_one_system_tip,
    inspect_exactly_one_system_tip_across_transactions,
    permit_request_from_payload,
    resubmission_decision,
    validate_permit_payload,
)

# ``RpcSender`` and ``JitoSender`` remain bound for explicit compatibility
# imports used by PR-045 tests and downstream code. New composition must use the
# canonical facade, so the concrete implementations are intentionally omitted
# from ``__all__``.
__all__ = [
    "AsyncJsonHttpTransport",
    "CanonicalPermitBoundSender",
    "CanonicalSenderConfig",
    "CanonicalStatusReport",
    "DurableSubmissionResult",
    "ErrorDisposition",
    "HttpResponse",
    "JitoCredentialMode",
    "JitoUuidAuth",
    "LivePermitIssuer",
    "LiveSubmissionPolicy",
    "PermitBoundSubmissionService",
    "PermitRequest",
    "ResubmissionDecision",
    "Sender",
    "SignedPayload",
    "SubmissionAck",
    "SubmissionError",
    "SubmissionErrorCode",
    "SubmissionObservation",
    "SubmissionPermit",
    "SubmissionState",
    "SubmissionStatusClient",
    "TipAccountSnapshot",
    "TipEvidence",
    "TransportKind",
    "classify_jito_bundle_status",
    "classify_jito_inflight_status",
    "classify_signature_statuses",
    "consolidate_submission_observations",
    "inspect_exactly_one_system_tip",
    "inspect_exactly_one_system_tip_across_transactions",
    "permit_request_from_payload",
    "resubmission_decision",
    "validate_permit_payload",
]
