"""PR-017/PR-042 append-only observability and health API."""

from .authoritative_store_pr195 import AuthoritativeObservabilityStore
from .cross_plane_pr196 import (
    AuthoritativeTruthBundle,
    CanonicalOutcome,
    CrossPlaneTerminalReconciler,
    CrossPlaneTruthError,
    CrossPlaneTruthStore,
    FinalizedSettlementEvidence,
    LedgerPostingEvidence,
    LifecycleTerminalEvidence,
    PlaneWatermark,
    ReconciliationResult,
    ReleasePolicyEvidence,
    ReservationTerminalState,
    TerminalTruthState,
    TruthPlane,
    VerifiedTerminalProjection,
)
from .events import (
    Environment,
    EventEnvelope,
    EventType,
    EvidenceRef,
    Outcome,
    PnL,
    Severity,
    make_event,
)
from .health import (
    DependencyState,
    DependencyStatus,
    RuntimeHttpConfig,
    RuntimeStatusHttpServer,
    build_health_payload,
    build_metrics_text,
    build_readiness_payload,
    build_status_payload,
    check_http_health,
)
from .reasons import REASON_REGISTRY, ReasonCode, classify_exception
from .store import ObservabilityError, ObservabilityStore

__all__ = [
    "AuthoritativeObservabilityStore",
    "AuthoritativeTruthBundle",
    "CanonicalOutcome",
    "CrossPlaneTerminalReconciler",
    "CrossPlaneTruthError",
    "CrossPlaneTruthStore",
    "DependencyState",
    "DependencyStatus",
    "Environment",
    "EventEnvelope",
    "EventType",
    "EvidenceRef",
    "FinalizedSettlementEvidence",
    "LedgerPostingEvidence",
    "LifecycleTerminalEvidence",
    "ObservabilityError",
    "ObservabilityStore",
    "Outcome",
    "PlaneWatermark",
    "PnL",
    "REASON_REGISTRY",
    "ReasonCode",
    "ReconciliationResult",
    "ReleasePolicyEvidence",
    "ReservationTerminalState",
    "RuntimeHttpConfig",
    "RuntimeStatusHttpServer",
    "Severity",
    "TerminalTruthState",
    "TruthPlane",
    "VerifiedTerminalProjection",
    "build_health_payload",
    "build_metrics_text",
    "build_readiness_payload",
    "build_status_payload",
    "check_http_health",
    "classify_exception",
    "make_event",
]
