from __future__ import annotations
from enum import Enum

class MarginfiRejectionCode(str, Enum):
    PIN_MISMATCH = "MARGINFI_PIN_MISMATCH"
    ACCOUNT_MISSING = "MARGINFI_ACCOUNT_MISSING"
    OWNER_MISMATCH = "MARGINFI_OWNER_MISMATCH"
    DISCRIMINATOR_MISMATCH = "MARGINFI_DISCRIMINATOR_MISMATCH"
    GROUP_MISMATCH = "MARGINFI_GROUP_MISMATCH"
    AUTHORITY_MISMATCH = "MARGINFI_AUTHORITY_MISMATCH"
    TOKEN_PROGRAM_MISMATCH = "MARGINFI_TOKEN_PROGRAM_MISMATCH"
    UNSUPPORTED_TOKEN = "MARGINFI_UNSUPPORTED_TOKEN"
    BANK_DISABLED = "MARGINFI_BANK_DISABLED"
    INSUFFICIENT_LIQUIDITY = "MARGINFI_INSUFFICIENT_LIQUIDITY"
    ORACLE_INVALID = "MARGINFI_ORACLE_INVALID"
    DUPLICATE_RISK_ACCOUNT = "MARGINFI_DUPLICATE_RISK_ACCOUNT"
    MIN_FINAL_BALANCE = "MARGINFI_MIN_FINAL_BALANCE"
    SEQUENCE_MUTATED = "MARGINFI_SEQUENCE_MUTATED"
    UNPROVEN_FEE = "MARGINFI_UNPROVEN_FEE"

class MarginfiRejection(ValueError):
    def __init__(self, code: MarginfiRejectionCode, diagnostic: str):
        super().__init__(f"{code.value}: {diagnostic}")
        self.code = code
        self.diagnostic = diagnostic
