"""Market Data Layer Evolution research-only bridge."""

from .contracts import (
    AvailabilityProof,
    ForecastRecord,
    GapEvent,
    InstrumentIdentity,
    MarketDataEvolutionError,
    MarketEpisode,
    ModelCandidate,
    NormalizedObservation,
    PredictiveRelation,
    QualificationEvidence,
    RawObservation,
    ReplayManifest,
    RetentionReport,
    SourceManifest,
    StateSnapshot,
    evaluate_retention,
    materialize_state,
    research_effect_boundary,
    select_as_of,
    stable_hash,
)
from .packs import (
    CrossMarketPack,
    all_cross_market_packs,
    build_crypto_derivatives_pack,
    build_gold_claim_pack,
    build_macro_vintage_pack,
    build_market_pack,
)

__all__ = [
    "AvailabilityProof",
    "CrossMarketPack",
    "ForecastRecord",
    "GapEvent",
    "InstrumentIdentity",
    "MarketDataEvolutionError",
    "MarketEpisode",
    "ModelCandidate",
    "NormalizedObservation",
    "PredictiveRelation",
    "QualificationEvidence",
    "RawObservation",
    "ReplayManifest",
    "RetentionReport",
    "SourceManifest",
    "StateSnapshot",
    "all_cross_market_packs",
    "build_crypto_derivatives_pack",
    "build_gold_claim_pack",
    "build_macro_vintage_pack",
    "build_market_pack",
    "evaluate_retention",
    "materialize_state",
    "research_effect_boundary",
    "select_as_of",
    "stable_hash",
]
