"""Production-grade paper/shadow runner boundary for PR-038/PR-089.

The package is intentionally sender-free.  It records durable lifecycle evidence
for the same high-level stages that live will later use, while fail-closing when
required upstream evidence is not present on the current branch.
"""

from src.paper_shadow.a2_exact_attempt_runtime import (
    A2PaperOutcomeStatus,
    ExactAttemptRuntimeItem,
    ExactAttemptRuntimePort,
    ExactAttemptRuntimeRecord,
    ExactAttemptRuntimeReport,
    run_exact_attempt_runtime_cycle,
)
from src.paper_shadow.a2_supported_paper_runtime import (
    A2_RECORDED_EVIDENCE_SCHEMA,
    A2_SQLITE_SCHEMA,
    A2_SUPPORTED_RUNTIME_SCHEMA,
    RecordedEvidenceCycle,
    RecordedEvidenceManifest,
    SupportedPaperRuntimeError,
    SupportedPaperRuntimeProfile,
    SupportedPaperRuntimeStore,
    SupportedPaperRuntimeSummary,
    load_recorded_evidence_manifest,
    manifest_from_json,
    report_from_json,
    run_supported_paper_runtime,
    run_supported_paper_runtime_from_manifest,
)
from src.paper_shadow.atomic_runtime_stages import (
    AtomicRuntimeStageError,
    AtomicRuntimeStageErrorCode,
    AtomicVerticalCandidateAdapter,
    AtomicVerticalRuntimeInputs,
    AtomicVerticalRuntimeStageSuite,
    AtomicVerticalStageRecord,
)
from src.paper_shadow.atomic_vertical import (
    AtomicPlannerSimulationReconciliationVertical,
    AtomicVerticalCandidate,
    AtomicVerticalError,
    AtomicVerticalRejectionCode,
    AtomicVerticalResult,
    AtomicVerticalTrace,
)
from src.paper_shadow.composition import (
    PR089_COMPOSITION_SCHEMA,
    PR089_MISSING_ATOMIC_DEPENDENCIES,
    PR102_COMPOSITION_SCHEMA,
    PR102_TYPE_SAFE_DEPENDENCY_REJECTED,
    ExactFeeCapitalWorkflowDependency,
    JupiterV2BuildDependency,
    PaperShadowDependencyGate,
    PaperShadowRuntime,
    PaperShadowRuntimeDependencies,
    VerifiedMarginfiProviderDependency,
    build_paper_shadow_runtime,
)
from src.paper_shadow.journal import JsonlPaperShadowJournal, PaperShadowEvent
from src.paper_shadow.runner import (
    PAPER_SHADOW_REQUIRED_STAGES,
    PaperShadowRunStatus,
    PaperShadowRunSummary,
    PaperShadowRunner,
    PaperShadowRunnerConfig,
    PaperShadowStageContext,
    PaperShadowStageName,
    paper_shadow_stage_blocked,
)

__all__ = [
    "A2PaperOutcomeStatus",
    "A2_RECORDED_EVIDENCE_SCHEMA",
    "A2_SQLITE_SCHEMA",
    "A2_SUPPORTED_RUNTIME_SCHEMA",
    "AtomicPlannerSimulationReconciliationVertical",
    "AtomicRuntimeStageError",
    "AtomicRuntimeStageErrorCode",
    "AtomicVerticalCandidate",
    "AtomicVerticalCandidateAdapter",
    "AtomicVerticalError",
    "AtomicVerticalRejectionCode",
    "AtomicVerticalResult",
    "AtomicVerticalRuntimeInputs",
    "AtomicVerticalRuntimeStageSuite",
    "AtomicVerticalStageRecord",
    "AtomicVerticalTrace",
    "ExactAttemptRuntimeItem",
    "ExactAttemptRuntimePort",
    "ExactAttemptRuntimeRecord",
    "ExactAttemptRuntimeReport",
    "ExactFeeCapitalWorkflowDependency",
    "JsonlPaperShadowJournal",
    "JupiterV2BuildDependency",
    "PAPER_SHADOW_REQUIRED_STAGES",
    "PR089_COMPOSITION_SCHEMA",
    "PR089_MISSING_ATOMIC_DEPENDENCIES",
    "PR102_COMPOSITION_SCHEMA",
    "PR102_TYPE_SAFE_DEPENDENCY_REJECTED",
    "PaperShadowDependencyGate",
    "PaperShadowEvent",
    "PaperShadowRunStatus",
    "PaperShadowRunSummary",
    "PaperShadowRunner",
    "PaperShadowRunnerConfig",
    "PaperShadowRuntime",
    "PaperShadowRuntimeDependencies",
    "PaperShadowStageContext",
    "PaperShadowStageName",
    "RecordedEvidenceCycle",
    "RecordedEvidenceManifest",
    "SupportedPaperRuntimeError",
    "SupportedPaperRuntimeProfile",
    "SupportedPaperRuntimeStore",
    "SupportedPaperRuntimeSummary",
    "VerifiedMarginfiProviderDependency",
    "build_paper_shadow_runtime",
    "load_recorded_evidence_manifest",
    "manifest_from_json",
    "paper_shadow_stage_blocked",
    "report_from_json",
    "run_exact_attempt_runtime_cycle",
    "run_supported_paper_runtime",
    "run_supported_paper_runtime_from_manifest",
]
