from pathlib import Path

from scripts.verify_pr008_supply_chain import verify

ROOT = Path(__file__).resolve().parents[2]


def test_shipped_supply_chain_objects_pass_static_controls() -> None:
    result = verify(ROOT)
    assert result["errors"] == []
    assert result["ready"] is False
    assert "pr007-final-parity-not-available" in result["blockers"]
    assert "requirements-dev.lock" in result["artifacts"]


def test_locks_include_resolved_transitive_dependencies() -> None:
    for lock_name in ("requirements.lock", "requirements-dev.lock"):
        lock = (ROOT / lock_name).read_text()
        assert "# This file is autogenerated by pip-compile with Python 3.13" in lock
    assert "click==" in (ROOT / "requirements-dev.lock").read_text()


def test_mutable_base_is_a_negative_control(tmp_path: Path) -> None:
    import shutil
    shutil.copytree(ROOT, tmp_path / "repo", ignore=shutil.ignore_patterns(".git", ".venv"))
    docker = tmp_path / "repo/Dockerfile"
    docker.write_text(docker.read_text().replace("python:3.13.13-slim-bookworm@sha256:", "python:3.13.13-slim-bookworm # ", 1))
    assert "every Docker stage must use the reviewed digest" in verify(tmp_path / "repo")["errors"]


def test_raw_environment_secret_is_a_negative_control(tmp_path: Path) -> None:
    import shutil
    shutil.copytree(ROOT, tmp_path / "repo", ignore=shutil.ignore_patterns(".git", ".venv"))
    compose = tmp_path / "repo/deploy/production/docker-compose.sandbox.yml"
    compose.write_text(compose.read_text() + "\n# runtime.env\n")
    assert "compose must omit raw env files and deny default egress" in verify(tmp_path / "repo")["errors"]
