"""Durable lifecycle primitives and the canonical roadmap PR-02 authority.

PR-182 keeps the PR-041 state machine as the lifecycle truth. PR-02 extends that
same SQLite product with provider/cycle intent, atomic terminal effects, and one
split producer/delivery outbox authority.
"""

from .lifecycle import (
    MIGRATION_VERSION,
    SCHEMA_NAME,
    AttemptKey,
    BackupManifest,
    CorruptJournalError,
    DuplicateSubmissionError,
    DurableAttempt,
    DurableLifecycleError,
    DurableLifecycleStore as LegacyDurableLifecycleStore,
    LeaseLostError,
    LeaseToken,
    OutboxItem,
    RecoveryAction,
    RecoveryDecision,
    ReservationState,
    UnsupportedTopologyError,
)
from .trusted_time_store import (
    ClockSafeDurableLifecycleStore,
    DurableLifecycleStore,
    PR182_DURABLE_TIME_SCHEMA,
)
from .single_truth import (
    PR121_BLOCKED_STATE,
    PR121_READY_STATE,
    PR121_RESULT_SCHEMA_VERSION,
    PR121_SCHEMA_VERSION,
    REQUIRED_BACKUP_FEATURES,
    REQUIRED_FAILURE_INJECTIONS,
    REQUIRED_OUTBOX_FEATURES,
    REQUIRED_RESTORE_FEATURES,
    REQUIRED_STATE_COMPONENTS,
    REQUIRED_TRANSACTION_BINDINGS,
    SingleTruthError,
    SingleTruthPackage,
    SingleTruthReadiness,
    SingleTruthReadinessState,
    assert_single_durable_lifecycle_truth,
    evaluate_single_durable_lifecycle_truth,
)
from .unified_authority_pr02 import (
    AuthorityFence,
    IntentKind,
    IntentStatus,
    PR02_PRODUCT_ID,
    PR02_SCHEMA_VERSION,
    ReservationTerminalState,
    TerminalCommit,
    UnifiedA3AdmissionSink,
    UnifiedAuthorityError,
    UnifiedLifecycleAuthority,
)

__all__ = [
    "MIGRATION_VERSION",
    "SCHEMA_NAME",
    "AttemptKey",
    "AuthorityFence",
    "BackupManifest",
    "ClockSafeDurableLifecycleStore",
    "CorruptJournalError",
    "DuplicateSubmissionError",
    "DurableAttempt",
    "DurableLifecycleError",
    "DurableLifecycleStore",
    "IntentKind",
    "IntentStatus",
    "LegacyDurableLifecycleStore",
    "LeaseLostError",
    "LeaseToken",
    "OutboxItem",
    "PR02_PRODUCT_ID",
    "PR02_SCHEMA_VERSION",
    "PR121_BLOCKED_STATE",
    "PR121_READY_STATE",
    "PR121_RESULT_SCHEMA_VERSION",
    "PR121_SCHEMA_VERSION",
    "PR182_DURABLE_TIME_SCHEMA",
    "REQUIRED_BACKUP_FEATURES",
    "REQUIRED_FAILURE_INJECTIONS",
    "REQUIRED_OUTBOX_FEATURES",
    "REQUIRED_RESTORE_FEATURES",
    "REQUIRED_STATE_COMPONENTS",
    "REQUIRED_TRANSACTION_BINDINGS",
    "RecoveryAction",
    "RecoveryDecision",
    "ReservationState",
    "ReservationTerminalState",
    "SingleTruthError",
    "SingleTruthPackage",
    "SingleTruthReadiness",
    "SingleTruthReadinessState",
    "TerminalCommit",
    "UnifiedA3AdmissionSink",
    "UnifiedAuthorityError",
    "UnifiedLifecycleAuthority",
    "UnsupportedTopologyError",
    "assert_single_durable_lifecycle_truth",
    "evaluate_single_durable_lifecycle_truth",
]
