"""Durable single-node lifecycle primitives introduced by roadmap PR-041.

PR-182 keeps the PR-041 state machine as the single lifecycle truth while making
its public store entrypoint boot-bound and monotonic for lease/outbox ownership.
"""

from .lifecycle import (
    MIGRATION_VERSION,
    SCHEMA_NAME,
    AttemptKey,
    BackupManifest,
    CorruptJournalError,
    DuplicateSubmissionError,
    DurableAttempt,
    DurableLifecycleError,
    DurableLifecycleStore as LegacyDurableLifecycleStore,
    LeaseLostError,
    LeaseToken,
    OutboxItem,
    RecoveryAction,
    RecoveryDecision,
    ReservationState,
    UnsupportedTopologyError,
)
from .trusted_time_store import (
    ClockSafeDurableLifecycleStore,
    DurableLifecycleStore,
    PR182_DURABLE_TIME_SCHEMA,
)
from .single_truth import (
    PR121_BLOCKED_STATE,
    PR121_READY_STATE,
    PR121_RESULT_SCHEMA_VERSION,
    PR121_SCHEMA_VERSION,
    REQUIRED_BACKUP_FEATURES,
    REQUIRED_FAILURE_INJECTIONS,
    REQUIRED_OUTBOX_FEATURES,
    REQUIRED_RESTORE_FEATURES,
    REQUIRED_STATE_COMPONENTS,
    REQUIRED_TRANSACTION_BINDINGS,
    SingleTruthError,
    SingleTruthPackage,
    SingleTruthReadiness,
    SingleTruthReadinessState,
    assert_single_durable_lifecycle_truth,
    evaluate_single_durable_lifecycle_truth,
)

__all__ = [
    "MIGRATION_VERSION",
    "SCHEMA_NAME",
    "AttemptKey",
    "BackupManifest",
    "ClockSafeDurableLifecycleStore",
    "CorruptJournalError",
    "DuplicateSubmissionError",
    "DurableAttempt",
    "DurableLifecycleError",
    "DurableLifecycleStore",
    "LegacyDurableLifecycleStore",
    "LeaseLostError",
    "LeaseToken",
    "OutboxItem",
    "PR121_BLOCKED_STATE",
    "PR121_READY_STATE",
    "PR121_RESULT_SCHEMA_VERSION",
    "PR121_SCHEMA_VERSION",
    "PR182_DURABLE_TIME_SCHEMA",
    "REQUIRED_BACKUP_FEATURES",
    "REQUIRED_FAILURE_INJECTIONS",
    "REQUIRED_OUTBOX_FEATURES",
    "REQUIRED_RESTORE_FEATURES",
    "REQUIRED_STATE_COMPONENTS",
    "REQUIRED_TRANSACTION_BINDINGS",
    "RecoveryAction",
    "RecoveryDecision",
    "ReservationState",
    "SingleTruthError",
    "SingleTruthPackage",
    "SingleTruthReadiness",
    "SingleTruthReadinessState",
    "UnsupportedTopologyError",
    "assert_single_durable_lifecycle_truth",
    "evaluate_single_durable_lifecycle_truth",
]
