#!/usr/bin/env python3
"""Fail-closed starter verifier for MPR-45 release bundle evidence.

The real implementation must load the release bundle generated by the installed
runtime/release pipeline and independently recompute every referenced digest.
This scaffold intentionally returns NOT_READY until concrete artifacts are wired.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


REQUIRED_ARTIFACT_KINDS = (
    "source_tree_digest",
    "wheel_digest",
    "image_digest",
    "dependency_lock_digest",
    "sbom",
    "provenance",
    "capability_manifest",
    "config_activation_receipt",
    "schema_fingerprint",
    "provider_protocol_evidence",
    "test_report",
    "soak_report",
    "fault_injection_report",
    "backup_restore_report",
)


@dataclass(frozen=True)
class VerificationResult:
    ok: bool
    status: str
    reason: str
    required_artifact_kinds: tuple[str, ...]
    inspected_path: str | None = None


def verify_release_bundle(bundle_path: Path | None) -> VerificationResult:
    if bundle_path is None:
        return VerificationResult(
            ok=False,
            status="NOT_READY",
            reason="release_bundle_path_required",
            required_artifact_kinds=REQUIRED_ARTIFACT_KINDS,
        )
    if not bundle_path.exists():
        return VerificationResult(
            ok=False,
            status="NOT_READY",
            reason="release_bundle_missing",
            required_artifact_kinds=REQUIRED_ARTIFACT_KINDS,
            inspected_path=str(bundle_path),
        )
    return VerificationResult(
        ok=False,
        status="NOT_IMPLEMENTED",
        reason="mpr45_release_bundle_verifier_scaffold_only",
        required_artifact_kinds=REQUIRED_ARTIFACT_KINDS,
        inspected_path=str(bundle_path),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", type=Path, default=None)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    result = verify_release_bundle(args.bundle)
    payload: dict[str, Any] = asdict(result)
    if args.json:
        print(json.dumps(payload, sort_keys=True, indent=2))
    else:
        print(f"{result.status}: {result.reason}")
    return 0 if result.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
